sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

services:
  - mongodb

before_install:
  - npm install mocha jshint -g

before_script:
  - mongo ExerciseApp_Test --eval 'db.addUser("testUser", "password");'


